In [225]:
from tabulate import tabulate
import numpy as np
import random

n_periods: int = 8

team_members: list[str] = [
    "Benjamin",
    "Vik",
    "Vigo",
    "Can",
    "Njabulo",
    "Lars",
    "Sebas",
    "Kees",
    "Hamza",
]

excl_team: list[str] = []

tasks_base = [
    "Keeper",
    "Aanvaller",
    "Middenvelder 1",
    "Middenvelder 2",
    "Verdediger 1",
    "Verdediger 2",
]

headers = [f"Periode {i + 1}" for i in range(n_periods)]

keepers: list[str] = ["Hamza", "Vik", "Vigo", "Njabulo"]
keeper_idx = [team_members.index(keeper) for keeper in keepers]
random.shuffle(keeper_idx)

team: list[str] = [i for i in team_members if i not in excl_team]
team_idx = [team_members.index(member) for member in team]
random.shuffle(team_idx)

n_team: int = len(team)  # Number of team members
n_tasks: int = len(tasks_base)  # Number of team positions
n_subs: int = n_team - n_tasks  # The number of subs

tasks_sub = [f"Wissel {i}" for i in range(1, n_subs + 1)]
tasks = tasks_base + tasks_sub

# Create the matrix where rows are n team members playing and columns the
# n of periods
matrix: np.array = np.full((n_team, n_periods), -99).astype(int)

In [226]:
# Set the keepers
matrix[0, np.arange(len(keeper_idx)) * 2] = keeper_idx
matrix[0, np.arange(len(keeper_idx)) * 2 + 1] = keeper_idx

matrix

array([[  4,   4,   8,   8,   1,   1,   2,   2],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99]])

In [227]:
# Set the substitutes for each period
sub_list: list = team_idx * (n_subs + 1)

for i in range(n_periods):
    for j in range(1, n_subs + 1):
        # t represents the first team member id from the list    
        t: int = sub_list[0]

        # Check if the team member is already in the column
        if np.isin(t, matrix[:,i]):
            # Take the next element in the list given t is Keeper    
            t = sub_list[1]
            # Check if team member was sub in previous period, if yes take next
            if np.isin(t, matrix[-n_subs:,i-1]):
                t = sub_list.pop(2)
            else:
                t = sub_list.pop(1)
            matrix[j * -1, i] = t
        else:
            sub_list.remove(t)
            matrix[j * -1, i] = t        

matrix

array([[  4,   4,   8,   8,   1,   1,   2,   2],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [  0,   8,   2,   0,   8,   6,   0,   4],
       [  5,   1,   3,   5,   4,   2,   5,   1],
       [  6,   7,   4,   6,   7,   3,   1,   7]])

In [228]:
# Aanvallers for each period
for i in range(n_periods):
    for j in range(5):
        print
    if (i+1) % 2 == 0:
        # We are substituting in the period
        # Get the previous attacker and check if he is substitute

        p_attack = matrix[1,i-1] # get attacker from previous period
        p_mid1 = matrix[2,i-1]
        # p_mid2 = matrix[3,i-1]
        # p_def1 = matrix[4,i-1]
        # p_def2 = matrix[5,i-1]
        print(p_attack)
        if p_attack in matrix[:,i]:
            print(f"the current attacker {team_members[p_attack]} is now sub in period {i+1}")
            loc_sub = np.where(matrix[:,i] == p_attack)[0][0]
            print(loc_sub)
            matrix[1,i] = matrix[loc_sub, i-1]
        else:
            matrix[1,i] = matrix[1, i-1]

        if p_mid1 in matrix[:,i]:
            print(f"the current Mid1 {team_members[p_mid1]} is now sub in period {i+1}")
            loc_sub = np.where(matrix[:,i] == p_mid1)[0][0]
            matrix[2,i] = matrix[loc_sub, i-1]
        else:
            matrix[2,i] = matrix[2, i-1]

    else:
        unique_values, counts = np.unique(np.append(matrix[1,:], team_idx), 
                                        return_counts=True)

        # Sort the unique values and their counts
        sorted_indices = np.argsort(counts)
        sorted_values = unique_values[sorted_indices]
   
        val = np.array([el for el in sorted_values if el not in matrix[:,i]])

        matrix[1,i] = val[0]
        matrix[2,i] = val[1]
matrix

1 0
1 1
1 2
1 3
1 4
1 0
1 1
1 2
1 3
1 4
1
the current attacker Vik is now sub in period 2
7
1 0
1 1
1 2
1 3
1 4
1 0
1 1
1 2
1 3
1 4
0
the current attacker Benjamin is now sub in period 4
6
the current Mid1 Sebas is now sub in period 4
1 0
1 1
1 2
1 3
1 4
1 0
1 1
1 2
1 3
1 4
6
the current attacker Sebas is now sub in period 6
6
the current Mid1 Can is now sub in period 6
1 0
1 1
1 2
1 3
1 4
1 0
1 1
1 2
1 3
1 4
4
the current attacker Njabulo is now sub in period 8
6


array([[  4,   4,   8,   8,   1,   1,   2,   2],
       [  1,   5,   0,   2,   6,   8,   4,   0],
       [  2,   2,   6,   4,   3,   7,   3,   3],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [-99, -99, -99, -99, -99, -99, -99, -99],
       [  0,   8,   2,   0,   8,   6,   0,   4],
       [  5,   1,   3,   5,   4,   2,   5,   1],
       [  6,   7,   4,   6,   7,   3,   1,   7]])

In [229]:
# Replace the index with the name of team members
matrix[matrix == -99] = 0
matrix_str = [[team_members[matrix[i][j]] for j in range(n_periods)] for i in range(n_team)]

# Add tasks row
[row.insert(0, task) for task, row in zip(tasks, matrix_str)]

print(tabulate(matrix_str, headers=headers, tablefmt="grid"))

+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
|                | Periode 1   | Periode 2   | Periode 3   | Periode 4   | Periode 5   | Periode 6   | Periode 7   | Periode 8   |
+================+=============+=============+=============+=============+=============+=============+=============+=============+
| Keeper         | Njabulo     | Njabulo     | Hamza       | Hamza       | Vik         | Vik         | Vigo        | Vigo        |
+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
| Aanvaller      | Vik         | Lars        | Benjamin    | Vigo        | Sebas       | Hamza       | Njabulo     | Benjamin    |
+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
| Middenvelder 1 | Vigo        | Vigo        | Sebas       | Njabulo     | Can     

In [230]:

unique_values, counts = np.unique(matrix[-n_subs:, :], return_counts=True)

# Combine the unique values and their counts into a dictionary for an overview
for value, count in zip(unique_values, counts):
    print(f"Value {team_members[value]}: {count} occurrences")




Value Benjamin: 3 occurrences
Value Vik: 3 occurrences
Value Vigo: 2 occurrences
Value Can: 2 occurrences
Value Njabulo: 3 occurrences
Value Lars: 3 occurrences
Value Sebas: 3 occurrences
Value Kees: 3 occurrences
Value Hamza: 2 occurrences


In [231]:
# Replace the index with the name of team members
matrix_str = [[team_members[matrix[i][j]] for j in range(n_periods)] for i in range(n_team)]

# Add tasks row
[row.insert(0, task) for task, row in zip(tasks, matrix_str)]

print(tabulate(matrix_str, headers=headers, tablefmt="grid"))

+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
|                | Periode 1   | Periode 2   | Periode 3   | Periode 4   | Periode 5   | Periode 6   | Periode 7   | Periode 8   |
+================+=============+=============+=============+=============+=============+=============+=============+=============+
| Keeper         | Njabulo     | Njabulo     | Hamza       | Hamza       | Vik         | Vik         | Vigo        | Vigo        |
+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
| Aanvaller      | Vik         | Lars        | Benjamin    | Vigo        | Sebas       | Hamza       | Njabulo     | Benjamin    |
+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
| Middenvelder 1 | Vigo        | Vigo        | Sebas       | Njabulo     | Can     