In [347]:
from tabulate import tabulate
from typing import List
import numpy as np

import random

n_periods: int = 8

team_members: List[str] = [
    "Benjamin",
    "Vik",
    "Vigo",
    "Can",
    "Njabulo",
    "Lars",
    "Sebas",
    "Kees",
    "Hamza",
]

excl_team: List[str] = ["Kees"]

tasks_base = [

    "Keeper",
    "Aanvaller",
    "Middenvelder 1",
    "Middenvelder 2",
    "Verdediger 1",
    "Verdediger 2",
]

headers = [f"Periode {i + 1}" for i in range(n_periods)]

keepers: List[str] = ["Hamza", "Vik", "Vigo", "Can"]
keeper_idx = [team_members.index(keeper) for keeper in keepers]
random.shuffle(keeper_idx)

team: List[str] = [i for i in team_members if i not in excl_team]
team_idx = [team_members.index(member) for member in team]
random.shuffle(team_idx)

n_team: int = len(team)  # Number of team members
n_tasks: int = len(tasks_base)  # Number of team positions
n_subs: int = n_team - n_tasks  # The number of subs

tasks_sub = [f"Wissel {i}" for i in range(1, n_subs + 1)]
tasks = tasks_base + tasks_sub
print(tasks)

# Create the matrix where rows are n team members playing and columns the
# n of periods
matrix: np.array = np.full((n_team, n_periods), -1).astype(int)

['Keeper', 'Aanvaller', 'Middenvelder 1', 'Middenvelder 2', 'Verdediger 1', 'Verdediger 2', 'Wissel 1', 'Wissel 2']


In [348]:
# Set the keepers
# Set values for keeper_idx in matrix at specific indices
matrix[0, np.arange(len(keeper_idx)) * 2] = keeper_idx
matrix[0, np.arange(len(keeper_idx)) * 2 + 1] = keeper_idx

matrix

array([[ 1,  1,  8,  8,  3,  3,  2,  2],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1]])

In [349]:
tmp_list = team_idx.copy()
# print(tmp_list)
# i = 0
# Set the substitutes
for i in range(n_periods):
    for j in range(1, n_subs + 1):
        if len(tmp_list) == 0:
            tmp_list = team_idx.copy()


        val = tmp_list[0]
        print(f"Looking at: {val}: {tmp_list}")

        if np.isin(val, matrix[:,i]):
            if len(tmp_list) == 1:
                tmp_list = tmp_list + team_idx
            val = tmp_list.pop(1)

            # print(f"Substitute {val} = Keeper, take next")
            # print(tmp_list)
            matrix[j * -1, i] = val
            print(matrix)
        else:
            tmp_list.remove(val)
            # print(f"Substitute: {val} is not Keeper, add")
            # print(tmp_list)
            matrix[j * -1, i] = val
            print(matrix)
        



matrix

Looking at: 2: [2, 4, 1, 6, 8, 5, 0, 3]
[[ 1  1  8  8  3  3  2  2]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [ 2 -1 -1 -1 -1 -1 -1 -1]]
Looking at: 4: [4, 1, 6, 8, 5, 0, 3]
[[ 1  1  8  8  3  3  2  2]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [ 4 -1 -1 -1 -1 -1 -1 -1]
 [ 2 -1 -1 -1 -1 -1 -1 -1]]
Looking at: 1: [1, 6, 8, 5, 0, 3]
[[ 1  1  8  8  3  3  2  2]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [ 4 -1 -1 -1 -1 -1 -1 -1]
 [ 2  6 -1 -1 -1 -1 -1 -1]]
Looking at: 1: [1, 8, 5, 0, 3]
[[ 1  1  8  8  3  3  2  2]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1]
 [ 4  8 -1 -1 -1 -1 -1 -1]
 [ 2  6 -1 -1 -1 -

array([[ 1,  1,  8,  8,  3,  3,  2,  2],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1],
       [ 4,  8,  5,  3,  4,  6,  5,  3],
       [ 2,  6,  1,  0,  2,  1,  8,  0]])

In [350]:


# # Set the substitutes
# for i in range(n_periods):
#     # Remove the keeper for the period
#     tp = [t for t in team_idx if t != matrix[0, i]]

#     # Set the substitutes
#     for j in range(1, n_subs + 1):
#         select = tp.pop(random.randrange(len(tp)))
#         matrix[j * -1, i] = select

#     # Set the other positions except for the keeper
#     for j in range(1, n_tasks):
#         select = tp.pop(random.randrange(len(tp)))
#         matrix[j, i] = select

# Replace the index with the name of team members

matrix_str = [[team_members[matrix[i][j]] for j in range(n_periods)] for i in range(n_team)]

# Add tasks row
[row.insert(0, task) for task, row in zip(tasks, matrix_str)]


print(tabulate(matrix_str, headers=headers, tablefmt="grid"))

+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
|                | Periode 1   | Periode 2   | Periode 3   | Periode 4   | Periode 5   | Periode 6   | Periode 7   | Periode 8   |
+================+=============+=============+=============+=============+=============+=============+=============+=============+
| Keeper         | Vik         | Vik         | Hamza       | Hamza       | Can         | Can         | Vigo        | Vigo        |
+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
| Aanvaller      | Hamza       | Hamza       | Hamza       | Hamza       | Hamza       | Hamza       | Hamza       | Hamza       |
+----------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+-------------+
| Middenvelder 1 | Hamza       | Hamza       | Hamza       | Hamza       | Hamza   

In [351]:
# Create a list
my_list = [1, 2, 3, 4, 5]

# Removes and returns the last element of the list
last_element = my_list.pop()
print(last_element)
tabulate(my_list)

5


TypeError: 'int' object is not iterable